///////////////////////////////////////////////////////////
//  AsignacionResponsableTecnicoRT.cs
//  Implementation of the Class AsignacionResponsableTecnicoRT
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:22
//  Original author: Nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class AsignacionResponsableTecnicoRT {

	private int fechaDesde;
	private int fechaHasta;
    private PersonalCientífico personalCientífico;
    private RecursoTecnologico recursoTecnologico;


	public void crear(){

	}

	public void mostrarResponsableTecnicoRT(){

	}

	public void misRT(){

	}

	public void esDeUsuarioLogueadoYVigente(){

	}

	public void esVigente(){

	}

}//end AsignacionResponsableTecnicoRT