///////////////////////////////////////////////////////////
//  AsignacionResponsableTecnicoRT.cs
//  Implementation of the Class AsignacionResponsableTecnicoRT
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:22
//  Original author: Nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class AsignacionResponsableTecnicoRT {

	private int fechaDesde;
	private int fechaHasta;
	public PersonalCientífico m_PersonalCientífico;
	public RecursoTecnologico m_RecursoTecnologico;

	public AsignacionResponsableTecnicoRT(){

	}

	~AsignacionResponsableTecnicoRT(){

	}

	public void crear(){

	}

	public void mostrarResponsableTecnicoRT(){

	}

	public void misRT(){

	}

	public void esDeUsuarioLogueadoYVigente(){

	}

	public void esVigente(){

	}

}//end AsignacionResponsableTecnicoRT