///////////////////////////////////////////////////////////
//  AsignacionCientificoDelCI.cs
//  Implementation of the Class AsignacionCientificoDelCI
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:18
//  Original author: Nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class AsignacionCientificoDelCI {

	private int fechaDesde;
	private int fechaHasta;
	public PersonalCientífico m_PersonalCientífico;
	public Turno m_Turno;

	public AsignacionCientificoDelCI(){

	}

	~AsignacionCientificoDelCI(){

	}

	public void crear(){

	}

	public void mostrarCientificoDelCI(){

	}

	public void esCientificoActivo(){

	}

	public void misTurnos(){

	}

}//end AsignacionCientificoDelCI