///////////////////////////////////////////////////////////
//  AsignacionDirectorCI.cs
//  Implementation of the Class AsignacionDirectorCI
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:21
//  Original author: Nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class AsignacionDirectorCI {

	private int fechaDesde;
	private int fechaHasta;
	public PersonalCientífico m_PersonalCientífico;

	public AsignacionDirectorCI(){

	}

	~AsignacionDirectorCI(){

	}

	public void crear(){

	}

	public void mostrarDirectorCI(){

	}

	public void esActual(){

	}

}//end AsignacionDirectorCI