///////////////////////////////////////////////////////////
//  CambioEstadoTurno.cs
//  Implementation of the Class CambioEstadoTurno
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:23
//  Original author: nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class CambioEstadoTurno {

	private int fechaHoraDesde;
	private int fechaHoraHasta;
	public Estado m_Estado;

	public CambioEstadoTurno(){

	}

	~CambioEstadoTurno(){

	}

	public void crear(){

	}

	public void mostrarCambioEstadoTurno(){

	}

	public void esVigente(){

	}

	public void esReservadoOPendiente(){

	}

	public void setFechaHoraDesde(){

	}

	public void setFechaHoraHasta(){

	}

	public void setEstado(){

	}

}//end CambioEstadoTurno