///////////////////////////////////////////////////////////
//  CambioEstadoRT.cs
//  Implementation of the Class CambioEstadoRT
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:22
//  Original author: Nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class CambioEstadoRT {

	private int fechaHoraDesde;
	private int fechaHoraHasta;
	public Estado m_Estado;

	public CambioEstadoRT(){

	}

	~CambioEstadoRT(){

	}

	public void crear(){

	}

	public void mostrarCambioEstadoRT(){

	}

	public void esActual(){

	}

}//end CambioEstadoRT