///////////////////////////////////////////////////////////
//  CaracteristicaRecurso.cs
//  Implementation of the Class CaracteristicaRecurso
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:24
//  Original author: leoav
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class CaracteristicaRecurso {

	private int valor;
	public Característica m_Característica;

	public CaracteristicaRecurso(){

	}

	~CaracteristicaRecurso(){

	}

	public void crear(){

	}

	public void mostrarCaracteristicaRecurso(){

	}

}//end CaracteristicaRecurso