///////////////////////////////////////////////////////////
//  Característica.cs
//  Implementation of the Class Característica
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:23
//  Original author: Nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Característica {

	private int nombre;
	private int descripcion;

	public Característica(){

	}

	~Característica(){

	}

	public void crear(){

	}

	public void mostrarCaracteristica(){

	}

}//end Característica