///////////////////////////////////////////////////////////
//  CentroInvestigacion.cs
//  Implementation of the Class CentroInvestigacion
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:25
//  Original author: Nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class CentroInvestigacion {

	private int nombre;
	private int sigla;
	private int direccion;
	private int edificio;
	private int piso;
	private int cordenadas;
	private int telefonosContacto;
	private int correoElectronicos;
	private int numeroResolucionCreacion;
	private int fechaResolucionCreacion;
	private int reglamento;
	private int caracteristicasGenerales;
	private int fechaAlta;
	private int tiempoAntelaciónReserva;
	private int fechaBaja;
	private int motivoBaja;
	public AsignacionDirectorCI m_AsignacionDirectorCI;
	public AsignacionCientificoDelCI m_AsignacionCientificoDelCI;
	public RecursoTecnologico m_RecursoTecnologico;

	public CentroInvestigacion(){

	}

	~CentroInvestigacion(){

	}

	public void crear(){

	}

	public void mostrarCI(){

	}

	public void miDirectorActual(){

	}

	public void misDirectores(){

	}

	public void estoyActivo(){

	}

	public void misCientificos(){

	}

	public void misCientificosActivos(){

	}

	public void misRecursosTecnologicos(){

	}

	public void miBaja(){

	}

}//end CentroInvestigacion