///////////////////////////////////////////////////////////
//  Estado.cs
//  Implementation of the Class Estado
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:25
//  Original author: Nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Estado {

	private int nombre;
	private int descripcion;
	private int ambito;
	private int esReservable;
	private int esCancelable;

	public Estado(){

	}

	~Estado(){

	}

	public void crear(){

	}

	public void mostrarEstado(){

	}

	public void esDisponible(){

	}

	public void esReservadoOPendiente(){

	}

	public void esAmbitoTurno(){

	}

	public void esAmbitoRT(){

	}

	public void esCancelado(){

	}

	public void esMantenimiento(){

	}

	public void finalizar(){

	}

}//end Estado