///////////////////////////////////////////////////////////
//  ExtensionMantenimiento.cs
//  Implementation of the Class ExtensionMantenimiento
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:26
//  Original author: romin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ExtensionMantenimiento {

	private int fecha;
	private int fechaFinPrevista;
	private int motivo;

	public ExtensionMantenimiento(){

	}

	~ExtensionMantenimiento(){

	}

	public void crear(){

	}

	public void mostrarMotivo(){

	}

}//end ExtensionMantenimiento