///////////////////////////////////////////////////////////
//  Facultad.cs
//  Implementation of the Class Facultad
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:26
//  Original author: Nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Facultad {

	private int nombre;
	private int domicilio;
	public PersonalCientífico m_PersonalCientífico;
	public CentroInvestigacion m_CentroInvestigacion;

	public Facultad(){

	}

	~Facultad(){

	}

	public void misCI(){

	}

	public void mostrarFacultad(){

	}

	public void crear(){

	}

}//end Facultad