///////////////////////////////////////////////////////////
//  GestorDeRegistroRTMantenimiento.cs
//  Implementation of the Class GestorDeRegistroRTMantenimiento
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:26
//  Original author: nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class GestorDeRegistroRTMantenimiento {

	private int fechaFinPrevista;
	private int sesionUsuarioLogueado;
	private int RTSeleccionado;
	private int recursosTecnologicos;
	private int motivoMantenimiento;

	public GestorDeRegistroRTMantenimiento(){

	}

	~GestorDeRegistroRTMantenimiento(){

	}

	public void registarIngresoRTEnMantenimientoCorrectivo(){

	}

	public void opcionRegistrarIngresoRTMantenimientoCorrectivo(){

	}

	public void agruparRTCategoria(){

	}

	public void obtenerUsuarioLogueado(){

	}

	public void tomarSeleccionRT(){

	}

	public void tomarFechaFinPrevista(){

	}

	public void tomarMotivo(){

	}

	public void buscarTurnosDeRT(){

	}

	public void ordenarTurnosXCientifico(){

	}

	public void tomarNotificacionIngresada(){

	}

	public void generarMantenimiento(){

	}

}//end GestorDeRegistroRTMantenimiento