///////////////////////////////////////////////////////////
//  HorarioRT.cs
//  Implementation of the Class HorarioRT
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:27
//  Original author: Nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class HorarioRT {

	private int diaSemana;
	private int horaDesde;
	private int horaHasta;
	private int vigenciaDesde;
	private int vigenciaHasta;

	public HorarioRT(){

	}

	~HorarioRT(){

	}

	public void crear(){

	}

	public void mostrarHorarioRT(){

	}

	public void soyHorarioRTVigente(){

	}

}//end HorarioRT