///////////////////////////////////////////////////////////
//  Mantenimiento.cs
//  Implementation of the Class Mantenimiento
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:27
//  Original author: romin
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Mantenimiento {

	private int fechaFin;
	private int fechaInicio;
	private int fechaInicioPrevista;
	private int motivoMantenimiento;
	public ExtensionMantenimiento m_ExtensionMantenimiento;

	public Mantenimiento(){

	}

	~Mantenimiento(){

	}

	public void crear(){

	}

	public void mostrarMantenimiento(){

	}

	public void iniciar(){

	}

	public void finalizar(){

	}

	public void esPreventivo(){

	}

	public void extender(){

	}

	public void calcularDuracionTotal(){

	}

}//end Mantenimiento