///////////////////////////////////////////////////////////
//  Marca.cs
//  Implementation of the Class Marca
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:27
//  Original author: Nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Marca {

	private int nombre;
	public Modelo m_Modelo;

	public Marca(){

	}

	~Marca(){

	}

	public void crear(){

	}

	public void mostrarMarca(){

	}

	public void mostrarMisModelos(){

	}

}//end Marca