///////////////////////////////////////////////////////////
//  Modelo.cs
//  Implementation of the Class Modelo
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:28
//  Original author: Nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Modelo {

	private int nombre;

	public Modelo(){

	}

	~Modelo(){

	}

	public void crear(){

	}

	public void mostrarModelo(){

	}

	public void mostrarMarcaYModelo(){

	}

}//end Modelo