///////////////////////////////////////////////////////////
//  PantallaRegistroRTMantenimiento.cs
//  Implementation of the Class PantallaRegistroRTMantenimiento
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:28
//  Original author: nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class PantallaRegistroRTMantenimiento {

	private int btnCancelacion;
	private int btnConfirmacion;
	private int btnRegistrarIngresoRT;

	public PantallaRegistroRTMantenimiento(){

	}

	~PantallaRegistroRTMantenimiento(){

	}

	public void habilitarPantalla(){

	}

	public void tomarFechaFinPrevista(){

	}

	public void tomarSeleccionRT(){

	}

	public void solicitarSeleccionRT(){

	}

	public void solicitarFechaFinPrevista(){

	}

	public void mostrarRecursosTecnologicos(){

	}

	public void seleccionarOpcionRegistrarIngresoRTMantenimiento(){

	}

	public void solicitarMotivo(){

	}

	public void tomarMotivo(){

	}

	public void mostrarTurnosXCientificos(){

	}

	public void solicitarConfirmacion(){

	}

	public void solicitarOpcNotificacion(){

	}

	public void tomarNotificacionIngresada(){

	}

}//end PantallaRegistroRTMantenimiento