///////////////////////////////////////////////////////////
//  PersonalCientífico.cs
//  Implementation of the Class PersonalCientífico
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:29
//  Original author: Nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class PersonalCientífico {

	private int legajo;
	private int nombre;
	private int apellido;
	private int numeroDocumento;
	private int correoElectronicoInstitucional;
	private int correoElectronicoPersonal;
	private int telefonoCelular;
	public Usuario m_Usuario;

	public PersonalCientífico(){

	}

	~PersonalCientífico(){

	}

	public void crear(){

	}

	public void mostrarPersonalCientifico(){

	}

	public void inhabilitarUsuario(){

	}

	public void habilitarUsuario(){

	}

	public void tengoUsuarioHabilitado(){

	}

	public void mostrarMisNovedades(){

	}

}//end PersonalCientífico