///////////////////////////////////////////////////////////
//  RecursoTecnologico.cs
//  Implementation of the Class RecursoTecnologico
//  Generated by Enterprise Architect
//  Created on:      08-jun.-2022 14:04:58
//  Original author: Nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class RecursoTecnologico {

	private int numeroRT;
	private int fechaAlta;
	private int imagenes;
	private int periodicidadMantenimientoPrev;
	private int duracionMantenimientoPrev;
	private int fraccionHorarioTurnos;
	public Modelo m_Modelo;
	public TipoRecursoTecnologico m_TipoRecursoTecnologico;
	public CaracteristicaRecurso m_CaracteristicaRecurso;
	public Mantenimiento m_Mantenimiento;
	public HorarioRT m_HorarioRT;
	public CambioEstadoRT m_CambioEstadoRT;
	public Turno m_Turno;

	public RecursoTecnologico(){

	}

	~RecursoTecnologico(){

	}

	public void crear(){

	}

	public void mostrarRT(){

	}

	public void habilitar(){

	}

	public void conocerCategoria(){

	}

	public void conocerCaracteristicaRecurso(){

	}

	public void miModeloyMarca(){

	}

	public void nuevoMantenimientoPreventivo(){

	}

	public void misTurnosDisponibles(){

	}

	public void estaDisponible(){

	}

	public void enMantenimiento(){

	}

	public void crearMantenimiento(){

	}

	public void cambiarEstado(){

	}

}//end RecursoTecnologico