///////////////////////////////////////////////////////////
//  Sesión.cs
//  Implementation of the Class Sesión
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:29
//  Original author: Nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Sesión {

	private int fechaFin;
	private int fechaInicio;
	private int horaFin;
	private int horaInicio;

	public Sesión(){

	}

	~Sesión(){

	}

	public void iniciarSesión(){

	}

	public void getPersonalCientificoEnSesion(){

	}

}//end Sesión