///////////////////////////////////////////////////////////
//  TipoRecursoTecnologico.cs
//  Implementation of the Class TipoRecursoTecnologico
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:29
//  Original author: Nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class TipoRecursoTecnologico {

	private int nombre;
	private int descripción;
	public Característica m_Característica;

	public TipoRecursoTecnologico(){

	}

	~TipoRecursoTecnologico(){

	}

	public void crear(){

	}

	public void mostrarCategoria(){

	}

	public void mostrarTipoRecurso(){

	}

}//end TipoRecursoTecnologico