///////////////////////////////////////////////////////////
//  Turno.cs
//  Implementation of the Class Turno
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:30
//  Original author: Nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Turno {

	private int fechaGeneracion;
	private int diaSemana;
	private int fechaHoraInicio;
	private int fechaHoraFin;
	public CambioEstadoTurno m_CambioEstadoTurno;

	public Turno(){

	}

	~Turno(){

	}

	public void crear(){

	}

	public void mostrarTurno(){

	}

	public void estoyDisponible(){

	}

	public void esAntesFechaFin(){

	}

	public void estaReservadoOPendiente(){

	}

	public void cancelarTurno(){

	}

}//end Turno