///////////////////////////////////////////////////////////
//  Usuario.cs
//  Implementation of the Class Usuario
//  Generated by Enterprise Architect
//  Created on:      29-may.-2022 13:52:30
//  Original author: Nahir
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Usuario {

	private int clave;
	private int usuario;
	private int habilitado;
	public Sesión m_Sesión;

	public Usuario(){

	}

	~Usuario(){

	}

	public void crear(){

	}

	public void habilitar(){

	}

	public void inhabilitar(){

	}

	public void modificarPassword(){

	}

	public void getCientifico(){

	}

}//end Usuario